name: build binary and attest
on:
  push:
    tags:
jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          depth: 0
      - name: Build and release Go
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
