name: build binary and attest
on:
  push:
    tags:
      - 't*'
jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          go build -o dist/test-github-provenance main.go
      - id: gh-release
        name: Publish GitHub release draft
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            fs = require('fs')
            res = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: '${{ github.ref_name }}',
              tag_name: '${{ github.ref }}',
              body: 'Release',
            });

            fs.readdirSync('dist/').forEach(file => {
              github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: res.data.id,
                name: file,
                data: fs.readFileSync('dist/' + file),
              });
            });

            return res.data.id
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: 'dist/*'
